/*===========================================================================
  TSG Consumer Partners — Step 4: Analytical Views
  Script: 04_create_views.sql
  
  Prerequisites: Run scripts 01-03 first
  Creates analytical views for reporting and ML feature engineering
===========================================================================*/

USE ROLE ACCOUNTADMIN;
USE DATABASE TSG_INTELLIGENCE;
USE SCHEMA ANALYTICS;
USE WAREHOUSE TSG_WH;

CREATE OR REPLACE VIEW V_PORTFOLIO_PERFORMANCE AS
SELECT
    pc.COMPANY_ID,
    pc.COMPANY_NAME,
    pc.SECTOR,
    pc.SUB_SECTOR,
    pc.STATUS,
    pc.INVESTMENT_DATE,
    pc.INVESTMENT_AMOUNT,
    pc.OWNERSHIP_STAKE,
    pc.HEADQUARTERS,
    pc.EMPLOYEE_COUNT,
    rd.FISCAL_YEAR,
    rd.FISCAL_QUARTER,
    rd.CHANNEL,
    rd.REGION,
    rd.REVENUE,
    rd.GROSS_PROFIT,
    rd.EBITDA,
    rd.NET_INCOME,
    rd.GROSS_MARGIN,
    rd.EBITDA_MARGIN,
    rd.REVENUE_GROWTH_YOY,
    id.VALUATION,
    id.ENTERPRISE_VALUE,
    id.EV_REVENUE_MULTIPLE,
    id.EV_EBITDA_MULTIPLE,
    id.IRR_PROJECTED,
    id.MOIC_PROJECTED,
    id.EXIT_STRATEGY
FROM PORTFOLIO_COMPANIES pc
LEFT JOIN REVENUE_DATA rd ON pc.COMPANY_ID = rd.COMPANY_ID
LEFT JOIN INVESTMENT_DEALS id ON pc.COMPANY_ID = id.COMPANY_ID;

CREATE OR REPLACE VIEW V_BRAND_ANALYTICS AS
SELECT
    pc.COMPANY_ID,
    pc.COMPANY_NAME,
    pc.SECTOR,
    pc.SUB_SECTOR,
    bm.METRIC_DATE,
    bm.BRAND_AWARENESS,
    bm.BRAND_SENTIMENT,
    bm.NET_PROMOTER_SCORE,
    bm.SOCIAL_FOLLOWERS,
    bm.SOCIAL_ENGAGEMENT,
    bm.SHARE_OF_VOICE,
    bm.BRAND_EQUITY_INDEX,
    bm.CUSTOMER_SAT_SCORE,
    mr.MARKET_SIZE_USD,
    mr.MARKET_GROWTH_RATE,
    mr.COMPETITIVE_POSITION,
    mr.CONSUMER_TREND
FROM PORTFOLIO_COMPANIES pc
LEFT JOIN BRAND_METRICS bm ON pc.COMPANY_ID = bm.COMPANY_ID
LEFT JOIN MARKET_RESEARCH mr ON pc.COMPANY_ID = mr.COMPANY_ID;

CREATE OR REPLACE VIEW V_REVENUE_GROWTH AS
SELECT
    pc.COMPANY_ID,
    pc.COMPANY_NAME,
    pc.SECTOR,
    rd.FISCAL_YEAR,
    rd.FISCAL_QUARTER,
    rd.CHANNEL,
    rd.REGION,
    rd.REVENUE,
    rd.GROSS_PROFIT,
    rd.EBITDA,
    rd.NET_INCOME,
    rd.GROSS_MARGIN,
    rd.EBITDA_MARGIN,
    rd.REVENUE_GROWTH_YOY,
    cp.CHANNEL_TYPE,
    cp.CHANNEL_REVENUE,
    cp.CHANNEL_MARGIN,
    cp.UNITS_SOLD,
    cp.RETURN_RATE,
    cp.CUSTOMER_COUNT,
    cp.REPEAT_PURCHASE_RATE
FROM PORTFOLIO_COMPANIES pc
LEFT JOIN REVENUE_DATA rd ON pc.COMPANY_ID = rd.COMPANY_ID
    AND rd.FISCAL_YEAR = rd.FISCAL_YEAR AND rd.FISCAL_QUARTER = rd.FISCAL_QUARTER
LEFT JOIN CHANNEL_PERFORMANCE cp ON pc.COMPANY_ID = cp.COMPANY_ID
    AND rd.FISCAL_YEAR = cp.FISCAL_YEAR AND rd.FISCAL_QUARTER = cp.FISCAL_QUARTER;

CREATE OR REPLACE VIEW V_ECOMMERCE_DIGITAL AS
SELECT
    pc.COMPANY_ID,
    pc.COMPANY_NAME,
    pc.SECTOR,
    da.METRIC_DATE,
    da.CHANNEL_NAME,
    da.WEBSITE_TRAFFIC,
    da.UNIQUE_VISITORS,
    da.BOUNCE_RATE,
    da.CONVERSION_RATE,
    da.AVG_ORDER_VALUE,
    da.CART_ABANDON_RATE,
    da.EMAIL_OPEN_RATE,
    da.EMAIL_CLICK_RATE,
    da.PAID_ROAS,
    da.ORGANIC_TRAFFIC_PCT,
    da.MOBILE_TRAFFIC_PCT,
    da.CUSTOMER_ACQ_COST,
    da.LTV_CAC_RATIO
FROM PORTFOLIO_COMPANIES pc
LEFT JOIN DIGITAL_ANALYTICS da ON pc.COMPANY_ID = da.COMPANY_ID;

CREATE OR REPLACE VIEW V_OPERATIONAL_EFFICIENCY AS
SELECT
    pc.COMPANY_ID,
    pc.COMPANY_NAME,
    pc.SECTOR,
    pc.SUB_SECTOR,
    om.METRIC_DATE,
    om.INVENTORY_TURNOVER,
    om.DAYS_SALES_OUTSTANDING,
    om.SUPPLY_CHAIN_SCORE,
    om.FULFILLMENT_RATE,
    om.ON_TIME_DELIVERY,
    om.COGS_PCT_REVENUE,
    om.SGA_PCT_REVENUE,
    om.CAPEX,
    om.WORKING_CAPITAL,
    om.CASH_CONVERSION
FROM PORTFOLIO_COMPANIES pc
LEFT JOIN OPERATIONS_METRICS om ON pc.COMPANY_ID = om.COMPANY_ID;

CREATE OR REPLACE VIEW V_BRAND_STRATEGY_KNOWLEDGE AS
SELECT
    bsd.DOC_ID,
    pc.COMPANY_NAME,
    pc.SECTOR,
    bsd.TITLE,
    bsd.CATEGORY,
    bsd.CONTENT,
    bsd.AUTHOR,
    bsd.PUBLISH_DATE,
    bsd.TAGS
FROM BRAND_STRATEGY_DOCS bsd
LEFT JOIN PORTFOLIO_COMPANIES pc ON bsd.COMPANY_ID = pc.COMPANY_ID;
