/*===========================================================================
  TSG Consumer Partners — Step 2: Table Definitions
  Script: 02_create_tables.sql
  
  Prerequisites: Run 01_database_and_schema.sql first
  Target Schema: TSG_INTELLIGENCE.ANALYTICS
===========================================================================*/

USE ROLE ACCOUNTADMIN;
USE DATABASE TSG_INTELLIGENCE;
USE SCHEMA ANALYTICS;
USE WAREHOUSE TSG_WH;

CREATE OR REPLACE TABLE PORTFOLIO_COMPANIES (
    COMPANY_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_NAME        VARCHAR(200) NOT NULL,
    SECTOR              VARCHAR(100),
    SUB_SECTOR          VARCHAR(100),
    INVESTMENT_DATE     DATE,
    INVESTMENT_AMOUNT   NUMBER(18,2),
    OWNERSHIP_STAKE     NUMBER(5,2),
    STATUS              VARCHAR(50) DEFAULT 'Active',
    HEADQUARTERS        VARCHAR(200),
    EMPLOYEE_COUNT      NUMBER,
    FOUNDED_YEAR        NUMBER(4),
    DESCRIPTION         VARCHAR(2000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BRAND_METRICS (
    METRIC_ID           NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_ID          NUMBER NOT NULL REFERENCES PORTFOLIO_COMPANIES(COMPANY_ID),
    METRIC_DATE         DATE NOT NULL,
    BRAND_AWARENESS     NUMBER(5,2),
    BRAND_SENTIMENT     NUMBER(5,2),
    NET_PROMOTER_SCORE  NUMBER(5,1),
    SOCIAL_FOLLOWERS    NUMBER,
    SOCIAL_ENGAGEMENT   NUMBER(8,2),
    SHARE_OF_VOICE      NUMBER(5,2),
    BRAND_EQUITY_INDEX  NUMBER(8,2),
    CUSTOMER_SAT_SCORE  NUMBER(5,2),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE REVENUE_DATA (
    REVENUE_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_ID          NUMBER NOT NULL REFERENCES PORTFOLIO_COMPANIES(COMPANY_ID),
    FISCAL_YEAR         NUMBER(4) NOT NULL,
    FISCAL_QUARTER      VARCHAR(2) NOT NULL,
    REVENUE             NUMBER(18,2),
    GROSS_PROFIT        NUMBER(18,2),
    EBITDA              NUMBER(18,2),
    NET_INCOME          NUMBER(18,2),
    GROSS_MARGIN        NUMBER(5,2),
    EBITDA_MARGIN       NUMBER(5,2),
    REVENUE_GROWTH_YOY  NUMBER(8,2),
    CHANNEL             VARCHAR(100),
    REGION              VARCHAR(100),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIGITAL_ANALYTICS (
    ANALYTICS_ID        NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_ID          NUMBER NOT NULL REFERENCES PORTFOLIO_COMPANIES(COMPANY_ID),
    METRIC_DATE         DATE NOT NULL,
    WEBSITE_TRAFFIC     NUMBER,
    UNIQUE_VISITORS     NUMBER,
    BOUNCE_RATE         NUMBER(5,2),
    CONVERSION_RATE     NUMBER(5,2),
    AVG_ORDER_VALUE     NUMBER(10,2),
    CART_ABANDON_RATE   NUMBER(5,2),
    EMAIL_OPEN_RATE     NUMBER(5,2),
    EMAIL_CLICK_RATE    NUMBER(5,2),
    PAID_ROAS           NUMBER(8,2),
    ORGANIC_TRAFFIC_PCT NUMBER(5,2),
    MOBILE_TRAFFIC_PCT  NUMBER(5,2),
    CUSTOMER_ACQ_COST   NUMBER(10,2),
    LTV_CAC_RATIO       NUMBER(8,2),
    CHANNEL_NAME        VARCHAR(100),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE MARKET_RESEARCH (
    RESEARCH_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_ID          NUMBER REFERENCES PORTFOLIO_COMPANIES(COMPANY_ID),
    RESEARCH_DATE       DATE NOT NULL,
    CATEGORY            VARCHAR(200),
    MARKET_SIZE_USD     NUMBER(18,2),
    MARKET_GROWTH_RATE  NUMBER(8,2),
    TAM_USD             NUMBER(18,2),
    SAM_USD             NUMBER(18,2),
    SOM_USD             NUMBER(18,2),
    COMPETITIVE_POSITION VARCHAR(50),
    KEY_COMPETITORS     VARCHAR(1000),
    CONSUMER_TREND      VARCHAR(500),
    INSIGHT_SUMMARY     VARCHAR(4000),
    SOURCE              VARCHAR(200),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CHANNEL_PERFORMANCE (
    CHANNEL_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_ID          NUMBER NOT NULL REFERENCES PORTFOLIO_COMPANIES(COMPANY_ID),
    FISCAL_YEAR         NUMBER(4) NOT NULL,
    FISCAL_QUARTER      VARCHAR(2) NOT NULL,
    CHANNEL_TYPE        VARCHAR(100) NOT NULL,
    CHANNEL_REVENUE     NUMBER(18,2),
    CHANNEL_MARGIN      NUMBER(5,2),
    UNITS_SOLD          NUMBER,
    AVG_SELLING_PRICE   NUMBER(10,2),
    RETURN_RATE         NUMBER(5,2),
    CUSTOMER_COUNT      NUMBER,
    NEW_CUSTOMER_PCT    NUMBER(5,2),
    REPEAT_PURCHASE_RATE NUMBER(5,2),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE OPERATIONS_METRICS (
    OPS_ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_ID          NUMBER NOT NULL REFERENCES PORTFOLIO_COMPANIES(COMPANY_ID),
    METRIC_DATE         DATE NOT NULL,
    INVENTORY_TURNOVER  NUMBER(8,2),
    DAYS_SALES_OUTSTANDING NUMBER(8,2),
    SUPPLY_CHAIN_SCORE  NUMBER(5,2),
    FULFILLMENT_RATE    NUMBER(5,2),
    ON_TIME_DELIVERY    NUMBER(5,2),
    COGS_PCT_REVENUE    NUMBER(5,2),
    SGA_PCT_REVENUE     NUMBER(5,2),
    CAPEX               NUMBER(18,2),
    WORKING_CAPITAL     NUMBER(18,2),
    CASH_CONVERSION     NUMBER(8,2),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE INVESTMENT_DEALS (
    DEAL_ID             NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_ID          NUMBER REFERENCES PORTFOLIO_COMPANIES(COMPANY_ID),
    DEAL_DATE           DATE NOT NULL,
    DEAL_TYPE           VARCHAR(100),
    DEAL_STAGE          VARCHAR(100),
    VALUATION           NUMBER(18,2),
    INVESTMENT_AMOUNT   NUMBER(18,2),
    EQUITY_PCT          NUMBER(5,2),
    ENTERPRISE_VALUE    NUMBER(18,2),
    EV_REVENUE_MULTIPLE NUMBER(8,2),
    EV_EBITDA_MULTIPLE  NUMBER(8,2),
    IRR_PROJECTED       NUMBER(8,2),
    MOIC_PROJECTED      NUMBER(8,2),
    HOLDING_PERIOD_YRS  NUMBER(4,1),
    EXIT_STRATEGY       VARCHAR(500),
    NOTES               VARCHAR(4000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BRAND_STRATEGY_DOCS (
    DOC_ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_ID          NUMBER REFERENCES PORTFOLIO_COMPANIES(COMPANY_ID),
    TITLE               VARCHAR(500) NOT NULL,
    CATEGORY            VARCHAR(200),
    CONTENT             VARCHAR(16000000),
    AUTHOR              VARCHAR(200),
    PUBLISH_DATE        DATE,
    TAGS                VARCHAR(1000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
